### ISSUE TITLE
脱出ハシゴがクリア条件の場合の水の描画の不具合

### ISSUE THREAD

**Issue by Tatamo** [Ryo-9399/mc_canvas#100]
脱出ハシゴがクリア条件で、背景レイヤーが無効・背景画像の表示のみが有効の場合、水の表示設定(レイヤー使用時でも常に水を表示する)にかかわらず水が描画されません。
同様に、緑色のブロックも描画されません。
また、その状態でも水に隣接するコインなどの背後には水が描画され、水しぶきが透明になっている緑ブロックにかかるとその時だけブロックが表示されます。
背景レイヤーが有効の場合でも、坂やハシゴの背後に水が描画されます。

https://masao.space/play/1743

**Comment by urotaichi** [comment]
Java版でも発生していたのを確認しました。
clear_typeの設定値3の説明文では「背景レイヤーの有無に関わらずハシゴ、坂道、下から通れるブロックを表示。」となっていますがソースコード中では「背景レイヤーの有無に関わらず、**背景レイヤーの表示を有効にすると消えるマップチップのうち**ハシゴ、坂道、下から通れるブロック**のみ**を表示。」となっているようですね。
https://github.com/Ryo-9399/mc_canvas/blob/b3fa1e50f6d856344f014bad538facdd9118a904/Sources/MapSystem.js#L278-L291
一番最初の条件式を背景レイヤーの使用の有無からではなく脱出ハシゴがクリア条件か否かで判断すれば行けそうな気もします。

**Comment by urotaichi** [comment]
追記
Java版からあるバグとして、
水を常に表示する設定にも関わらずハシゴや上り坂や下り坂では水マップチップを隣接させたにも関わらず背景に水が表示されません。
これも不自然なので直してしまっても問題ないような気がしますが。
