### ISSUE TITLE
効果音ファイルが正しく設定されていない

### ISSUE THREAD

**Issue by StickStickStick** [Ryo-9399/mc_canvas#102]
filename_se で始まるparamに効果音ファイル名を設定しても正しく反映されず、
既存の設定が読み込まれてしまいます。

例：https://kasomura.nobody.jp/masao/test/test1.html
全ての効果音を「hit81.wav」に設定したが、反映されていない

**Comment by urotaichi** [comment]
多分、#65 が原因です

**Comment by StickStickStick** [comment]
#65 と同じ件みたいなのでクローズします（お騒がせしてすみません）
