### ISSUE TITLE
カイオールのバブル光線系の攻撃の角度がJava版と異なる

### ISSUE THREAD

**Issue by bikkuri7** [Ryo-9399/mc_canvas#113]
かなり前からCanvas版で発生していた現象ですが報告していなかったので報告です。
カイオールの「バブル光線」「バブル光線連射」「バブル光線回転連射」の攻撃の角度がJava版と異なっています。
下は「バブル光線」の場合の例です。
![無題](https://user-images.githubusercontent.com/3896058/76723922-5bb6a400-678c-11ea-8957-3d0f76572f56.png)

**Comment by urotaichi** [comment]
[canvasまさおアップローダ](https://ux.getuploader.com/canvasmasao/)にあった一番古いmc_canvas_0000.zipで発生していたことを確認しました。
![image](https://user-images.githubusercontent.com/2631789/76762832-60537a80-67d5-11ea-9496-b06980ae7b58.png)

**Comment by urotaichi** [comment]
discordでの議論の結果、
Canvasまさおの一番最初のバージョンから発生していたバグであり、修正すると特に自動正男への影響が大きいことから、
カイオールのバブル光線は、`CanvasMasao.Game.replace`または`CanvasMasao.Game.replaceAll`を使った場合は**デフォルトでJava版の動作**を行い、`new CanvasMasao.Game`でまさおを生成した場合は**従来通りの動作**を行わせようと思います。
これにより、Java版からの変換は容易になり、また、既存のCanvasまさおユーザーがCanvasまさお本体データのアップデートを行った場合もわざわざJava版の動作との違いを考える必要もなくなります。
ちなみに両者ともオプションで動作を変更できるようにする予定です。
