### ISSUE TITLE
取得したクリック位置のずれ

### ISSUE THREAD

**Issue by shpqg** [Ryo-9399/mc_canvas#14]
お初にお目にかかります。GameMouseのmousePressedメソッドで取得しているマウスのクリック位置について，ゲーム画面左上の座標を引き忘れています。たとえばですが，<pre><code>GameMouse.prototype.mousePressed = function(paramMouseEvent) {
    var rect = paramMouseEvent.target.getBoundingClientRect();
    this.button_f = true;
    this.click_x = paramMouseEvent.clientX - rect.left;
    this.click_y = paramMouseEvent.clientY - rect.top;
}</code></pre>とすることで正常に動作しました(タイトル画面右端をクリックして正常にゲームが始まることを確認)。

**Comment by Ryo-9399** [comment]
ご指摘ありがとうございます。例のままでは拡大率が1.0以外の時にもずれてしまうので、これも合わせて修正しました。
