### ISSUE TITLE
効果音やBGMが再生されない

### ISSUE THREAD

**Issue by urotaichi** [Ryo-9399/mc_canvas#160]
ローカル環境以外で効果音やBGMが再生されなくなっています。

ソースコードをTypeScript 化した時から発生しているようです。

オプションでWebAudioを用いないに設定した場合は発生しません。

**Comment by urotaichi** [comment]
コンパイラの問題なのかは分からないですが、
GameSoundForApplet.tsの
https://github.com/Ryo-9399/mc_canvas/blob/22db4bd15e542dd1dc177b72934825066b950ab5/Sources/GameSoundForApplet.ts#L350-L351
を
```
s_data_wa: (AudioBuffer | null)[] = [];
bgm_wa: (AudioBuffer | null)[] = [];
```
に置き換え、
https://github.com/Ryo-9399/mc_canvas/blob/22db4bd15e542dd1dc177b72934825066b950ab5/Sources/GameSoundForApplet.ts#L359-L360
を削除したところ、音が正常に鳴りました。

ただし、コンソール上でエラーは発生したままです。

**Comment by Ryo-9399** [comment]
調査ありがとうございます。少し深掘りしてみました。

s_data_wa, bgm_wa という配列を追加したのは 9e1fdb2 で、結論を言うと **本来は不要です** 。しかし、この2つの配列を追加しない場合、継承元のフィールド s_data, bgm の要素の型を、継承元と先で AudioClip 型と AudioBuffer 型に切り替える必要がありました。当時よく分かっていないまま中途半端に実装したものが悪さをしていました。（完全に私の怠慢です）

修正方針としては「s_data_wa, bgm_wa を削除して s_data, bgm を使う設計に戻す」とするほうがいいと思いますが、型をうまく切り替える方法がすぐに思いつかないのでちょっと検討します。

# 不具合の原因

> GameSoundForApplet.tsの
> mc_canvas/Sources/GameSoundForApplet.ts
> 
> Lines 350 to 351 in 22db4bd
> 
>  s_data_wa: (AudioBuffer | null)[]; 
>  bgm_wa: (AudioBuffer | null)[]; 
> 
> を
> s_data_wa: (AudioBuffer | null)[] = [];
> bgm_wa: (AudioBuffer | null)[] = [];
> に置き換え、
> mc_canvas/Sources/GameSoundForApplet.ts
> 
> Lines 359 to 360 in 22db4bd
> 
>  this.s_data_wa = []; 
>  this.bgm_wa = []; 
> 
> を削除したところ、音が正常に鳴りました。
> 
> ただし、コンソール上でエラーは発生したままです。

この原因ですが、この修正を加えないまま `new GameSoundWebAudio` を実行すると、コンストラクタ最初の `super(...)` や `call` が、 s_data_wa, bgm_wa が `undefined` のまま実行され、そのままオーバーライドされたメソッド `_load` が呼ばれ、ここで s_data_wa, bgm_wa が捕捉されます。コンソール上のエラーの原因は

https://github.com/Ryo-9399/mc_canvas/blob/22db4bd15e542dd1dc177b72934825066b950ab5/Sources/GameSoundForApplet.ts#L442

この文に差し掛かった時に引数の target が `undefined` だったためです。そして再生されないのはコンストラクタ最後の s_data_wa, bgm_wa への `[]` 代入で初めて初期化されて空の状態になっていたためです。

引用の修正後、フィールドの初期化が

https://github.com/Ryo-9399/mc_canvas/blob/22db4bd15e542dd1dc177b72934825066b950ab5/Sources/GameSoundForApplet.ts#L355

の前に実行され、この文が実行される時には s_data_wa, bgm_wa が `[]` に初期化されているため正常にロードが成功し（たように見え）ます。

ちなみに、上に挙げた行 355 は継承をクラスに置き換える際に削除し忘れたものです。（これも私の確認漏れです）
