### ISSUE TITLE
「全方向進行用の視界」の設定時に仕掛けで左進行用/右進行用に切り替えると視界が揺れる

### ISSUE THREAD

**Issue by bikkuri7** [Ryo-9399/mc_canvas#225]
表示領域の動き方を「全方向進行用の視界」に設定している時に仕掛けの「画面内で左進行用の視界」や「画面内で右進行用の視界」を使用すると，地震のように視界が揺れます。
(v5.4.0)

**Comment by urotaichi** [comment]
scroll_areaでスクロール範囲を固定していた場合でも同様の現象が発生していたので、
合わせて修正したいと思います。

**Comment by urotaichi** [comment]
修正完了しました。
現時点では仕掛けを使用した後に「全方向進行用の視界」に戻す手段がありませんが、
要望があれば追加したいと思います。
