### ISSUE TITLE
フォントの自在変更機能の実装

### ISSUE THREAD

**Issue by Ryo-9399** [Ryo-9399/mc_canvas#26]
スコア、一言メッセージのフォントを、CSS形式で指定できるようにする。パラメータ名はそれぞれfont_score、font_messageにする。デフォルト値はそれぞれ"'Helvetica','Arial','ＭＳ ゴシック','HG ゴシックB Sun','HG ゴシックB',monospace"、"sans-serif"とする。

**Comment by urotaichi** [comment]
一言メッセージのフォントはブラウザのデフォルトだとWindowsではJava版のフォントのデフォルトフォントであるArialとＭＳ ゴシックが読み込まれなくなっているので
初期値は`"Arial,'ＭＳ ゴシック',sans-serif"`を提案します。
尤も、SANS_SERIFの初期値に関してはこの部分を直接直した方が良い気もしますがhttps://github.com/Ryo-9399/mc_canvas/blob/e41dd2ee4cfc0a833331991c378143136851614b/Sources/ImageBuff.js#L385
