### ISSUE TITLE
チコリンの攻撃が一部反映されないバグ

### ISSUE THREAD

**Issue by urotaichi** [Ryo-9399/mc_canvas#39]
chikorin_attackに5（マリリを無限に投げる）を設定した場合、昔のバージョンでは反映されていたのですが
最新のv1.00.0ではなぜかデフォルトの攻撃になってしまうようです。
バグだと思うので、修正お願いします。

**Comment by uhyo** [comment]
配布版がどのビルドか把握していませんが、revoブランチの最新版では再現しませんでした。
恐らく https://github.com/Ryo-9399/mc_canvas/commit/a7888405e67f7d82410846e90dc38de981a5c494 で修正済です。

**Comment by urotaichi** [comment]
調べてみたら今年の1月には既に解決済みの問題だったのですね。（ただし配布版が更新されたのが1月9日、バグが修正されたのが1月21日だったので後一歩遅かった）
お騒がせして申し訳ありませんでした。
