### ISSUE TITLE
UserJS内でエラーがthrowされるとゲームごと落ちる

### ISSUE THREAD

**Issue by Tatamo** [Ryo-9399/mc_canvas#51]
f83e148ca48a3069cb9ba92b09b45aac745b0d32 までは、UserJS内でエラーが発生しても次のフレーム以降は正しく動作していました。
020263aef8d6af7659f813284597bb911081eee1 のコミット以後、UserJS内でエラーが起きるとそこでゲーム全体が停止するようになっています。

**Comment by uhyo** [comment]
従来はsetIntervalを使ってループを回していたのに対し、
その変更以降はrequestAnimationFrameを使用しているので次のループが登録されるのがuserJS等の処理後になっているのが原因と思われます。
正直userJSがエラーを投げたら止まってもよいとは思いますが、userJS呼び出しをtryで囲めば直るはずです。

**Comment by Tatamo** [comment]
確かにcanvas正男の古いバージョンと比べれば挙動が変化しているものの、Javaアプレット版との互換性とは別の問題なので、エラーが出ても止まらずに動くのが望ましい挙動なのかどうかは一考の余地がありそうですね。
修正のマージの前に、もう少し検討したほうがいいかもしれません。

**Comment by Tatamo** [comment]
実際のところ、JS拡張を書く分にはエラーが発生した時点で止まってくれた方が失敗していることが分かりやすいかもしれません。
ところで http://space.geocities.jp/romsord/new_z_masao_276.html を最新の[canvasmasaoconverter](https://github.com/uhyo/canvasmasaoconverter)で動かしてみたところ、Applet1.getAudio()で取得したオブジェクトのPlay()メソッドを呼び出そうとしてエラーが発生してゲームが停止しました。
実際のところこれは https://github.com/uhyo/canvasmasaoconverter 側のダミーオブジェクトの問題ではあるのですが、Applet1.getAudio()はMasaoJSSではなくそのスーパークラスのjava.applet.Appletのメソッドです。
この例のようにJavaアプレットの継承元クラスのメソッドの呼び出しまで互換性を保とうとするのは困難であり、このような原因で発生したエラーによって遊べなくなってしまうゲームが存在する恐れがあります。
