### ISSUE TITLE
新しいビルド方法の導入について

### ISSUE THREAD

**Issue by Tatamo** [Ryo-9399/mc_canvas#53]
ソースコードの改修とメンテナンス性の向上は大きな課題ですが、それに取り組むためにも効率的なビルド方法を確立させることは重要であると思います。
そのための議論と方向性の決定のためにこのissueを建てました。

**Comment by Tatamo** [comment]
さらに追加ですが、Outputs/以下の成果物はこの開発用のリポジトリ(またはブランチ)には含まれないほうがよいのではないかと思っています。
ブランチが枝分かれした場合に基本的にOutputs以下でコンフリクトが起きるためです。

理想的には、このリポジトリ内にはソースコードとそれに必要なものだけを置くことが望ましいと考えています。

たとえば、コミットを検知してbotが自動的に別のリポジトリ/ブランチにビルド結果をコミットするような仕組みを検討してもよいと思います。

つまり、このリポジトリを開発用の環境を持たない人がダウンロードしても正男が動かせる、というような状態であることを求めるべきではなく、配布用のパッケージはまた別に用意されるべきで、そしてそれは可能なら自動的に生成されるものであることが望ましいのではないかと思います。

**Comment by uhyo** [comment]
現状だとgulpは導入しなくても、npm scriptsとwebpackで何とかなると思います。

新しいビルド方法でやりたいこととしては、バージョン情報を生成物に含めたいです（`CanvasMasao.version`みたいな感じ）。
バージョン番号をどう管理するかは別の問題としても、コミットのハッシュとか日時を含めることはできると思います。

**Comment by Tatamo** [comment]
Lintツールや.editorconfigの導入によってコーディング規約を明示、または強制するのはどうでしょうか？
常にコードスタイルが統一されるようにすればコミットの差分も見やすくなりますが、ある程度機械的に整形できるとはいえ既存コードが膨大なのでこれを何らかの規約に沿わせるだけでも大変な気もします。

**Comment by uhyo** [comment]
.editorconfigくらいは欲しいなと思っています。
Lintツールの導入もいいですが、手で修正が必要になるルールは修正箇所が膨大になることが予想されるので追い追いだと思います。

**Comment by Ryo-9399** [comment]
とりあえずwebpackとBabelとgulpを導入してみました。

`gulp` コマンドでFX版のビルドを実行します。また、2.8版ビルドの `v28` 、両方ビルドの `all` タスクも定義してあります。

他に「こうしたほうがいい」があれば意見をください。

**Comment by uhyo** [comment]
いいと思います。まだちゃんと調べていないですが、とりあえず気になった点を2つ。

- https://new.babeljs.io/docs/en/next/babel-preset-env.html によると今は`babel-preset-env`ではなく`@babel/preset-env`のほうが新しいようです。
- ブラウザターゲットの設定をちゃんとしたほうがいいようです。現在だと、IE9とか向けのPolyfillが入って無駄に容量が肥大化すると思います。ターゲットブラウザはIE11以上と他のブラウザは最新版という感じでしょうか。

**Comment by Tatamo** [comment]
全体的にとてもよいとおもいます。

https://github.com/Ryo-9399/mc_canvas/blob/384d89fe615f4d5a9229097347fc0a7d40420cca/Sources/index.js によって得られるCanvasMasaoとJSMasaoのオブジェクトの中身が https://github.com/Ryo-9399/mc_canvas/blob/384d89fe615f4d5a9229097347fc0a7d40420cca/Sources/post.js による生成結果と異なりますが、問題は起きないのでしょうか。
たとえば`JSMasao.MasaoConstruction`はundefinedになります。

**Comment by uhyo** [comment]
https://github.com/Ryo-9399/mc_canvas/issues/53#issuecomment-391934750

> 新しいビルド方法でやりたいこととしては、バージョン情報を生成物に含めたいです（CanvasMasao.versionみたいな感じ）。
バージョン番号をどう管理するかは別の問題としても、コミットのハッシュとか日時を含めることはできると思います。

これですが、 #54 が解決された後に取り組むべき問題という気がするので後回しでよいと思います。
残っている問題は主にlintツールや.editorconfigの問題なのでそれらを解決していこうと思います。

**Comment by uhyo** [comment]
現状のソースはタブとスペースが統一されていないようです。
その他にも細かいコーディングスタイルのばらつきがあり、これらは.editorconfigやlintツールの導入と同時に統一したほうがよいと思います。
この作業はコードの全体的な変更を伴うので、`refactoring/build-env`を`master`にマージしてしまってから別のissueを建てて行うとよいと思います。
なので`refactorig/build-env`はもうマージしてしまってよいと思います。

**Comment by Ryo-9399** [comment]
ありがとうございます。

では `refactoring/build-env` はマージし、残りの課題については別のissueを建てますのでそこで議論しましょう。本issueは新issue作成次第クローズさせていただきます。
