### ISSUE TITLE
Safariで音が鳴らない

### ISSUE THREAD

**Issue by uhyo** [Ryo-9399/mc_canvas#56]
BGMや効果音がMacやiOSのSaffariでは鳴らないという報告があります。

**Comment by uhyo** [comment]
SafariのAuto-Play Blocking機能やiOS10のインライン再生のポリシーにひっかかっているようです。

**Comment by urotaichi** [comment]
Web Audio APIを使えばそういった制約にとらわれず鳴らすことができるようです。ただし、IE等、一部のブラウザではWeb Audio APIが使えないので従来の方法も残しておいた方がいいと思います。

**Comment by uhyo** [comment]
最新版ではすでにWeb Audio APIが使われていますが、それでSafariでちゃんと音がなるかどうかは未検証です。
鳴らない可能性もあるのではないかと思っています。

**Comment by urotaichi** [comment]
少なくともiPhoneのSafariで試したところ効果音が鳴りませんでした。

https://qiita.com/pentamania/items/2c568a9ec52148bbfd08
このサイトによれば、一度無音再生後、ユーザー側でアクションを起こせば好きなタイミングで効果音を鳴らすことが、できるようです。
個人的にはバーチャル操作パッドをユーザーアクションにより表示したタイミングで無音再生させるのが良いと思いした。

**Comment by uhyo** [comment]
Chrome70からSafariと同様の措置がとられるらしいので、遅くとも10月までに対策が必要となりそうです。
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#webaudio
