### ISSUE TITLE
効果音ファイル名の指定方法が仕様と違うバグ

### ISSUE THREAD

**Issue by Tatamo** [Ryo-9399/mc_canvas#65]
## se_filename パラメータの挙動が仕様と異なる
http://fukuda.ec-net.jp/naoto/j_mcfx/game14.html のHTML内のコメント等からわかるように、
se_filenameパラメータの値は `"1"`のとき「ファイル名を記述して指定する」で、
`"2"`(初期値)のとき「デフォルトのファイル名と指定にする」です。

https://github.com/Ryo-9399/mc_canvas/blob/8781938b5a95575dd1d54d7ef2680ac27c2359be/Sources/GameSoundForApplet.js#L47
の実装は明らかにその反対となっています。

**Comment by urotaichi** [comment]
これって結局のところ反対のままなんでしょうか？

**Comment by Tatamo** [comment]
できる限り早めに直したいところではあるのですが、canvas版ではずっとこうなっていたかもしれず、急に挙動を変えてしまうと影響が大きそうなので放置していました。

今見たら、どうも2年ほど前の 8db4024714e75a0fd253795faffb925fab8ceb4c で動作が逆になったようで、
その時は誰も騒がなかったので意外と修正しても大丈夫な気がしてきました

**Comment by Tatamo** [comment]
とはいえバージョン番号の管理がなされていない現状のリリースサイクルでは混乱を生む恐れが否めないので、もう少し進展してから修正したほうが良いかなと思っています。

**Comment by urotaichi** [comment]
Java版のソースを見たところ、そもそもJava版FXからのバグで、
Java版より前ではse_filenameの初期値が2（ e87131b より前　デフォルトのファイル名と指定にする）なのが
Java版FXからはse_filenameの初期値が1（ e87131b より前　ファイル名を記述して指定する）だったようです。
e87131b から指定方法が逆になってしまったのはこれが原因の可能性があります。

とはいえやはり指定方法が逆のままでは混乱を生むので修正したほうがよさそうです。
また、初期値もFX以前のものに変更します。

**Comment by shpqg** [comment]
affects compatibilityのものをまともに議論せずに修正してしまって大丈夫なんですか？

**Comment by urotaichi** [comment]
#113 とは違って
効果音を使用した正男自体が少ない
効果音のファイル名を変更した正男はさらに少ない
ことから影響範囲は少ないことから修正しました。

**Comment by shpqg** [comment]
聞きたいのは修正理由ではないということを理解していただけず残念です（尚，個人的には上記やDiscordで提案されているバージョニングの導入時であれば賛成できました）。
率直に言って後方互換性を損なう変更が「あなたがそう思った」という理由だけで為されるのはちょっと怖いですが，レビュワーを確保できないのも事実ですからね。私はCollaboratorでもないのであまり強く言う気もありません。

**Comment by urotaichi** [comment]
すみません。
元から後方互換性を損なっていたものを戻す際も気を付けた方が良いということですね。
今更ですがもっと早めにバージョンを上げておけばよかったと思いました。

今後の方針として、また互換性に関する・影響が生じる変更が発生する可能性があるので[v5.0.0](https://github.com/Ryo-9399/mc_canvas/tree/v5.0.0)ブランチを作成し、そこで開発を続けていきたいと考えています。
開発が落ち着いたころには@Ryo-9399さんがいない中で勝手にやっていいのか分かりませんが [releases](https://github.com/Ryo-9399/mc_canvas/releases)で本体ファイルであるCanvasMasao.jsとCanvasMasao_v28.jsを公開し、前バージョン（v4.0.0）との変更点を明確に記載しようと思います。
ここでいう前バージョンとは、https://github.com/Ryo-9399/mc_canvas/commit/0059376d04289debb693dfb14b2b5e5564da27f6 時点でのCanvasMasao.jsとCanvasMasao_v28.jsを指します。


> 私はCollaboratorでもないのであまり強く言う気もありません。

いえ、こうして暴走してしまったときに誰か一人でも止めてくれる方がいるだけで助かります。
今後も率直なご意見を出していただければ幸いです。
