### ISSUE TITLE
地図画面正男でスコア表示がされなくなるバグ

### ISSUE THREAD

**Issue by urotaichi** [Ryo-9399/mc_canvas#84]
68a8e7f までは地図画面でスコアや残り人数が表示されていましたが、 b9e0ef7 からはscore_vで得点の表示する設定にしているにもかかわらずスコアが表示がされず、残り人数のみが表示されてしまいます。
このままでは地図画面上で得点とアイテムを交換できる店が使いにくくなってしまいます。
![image](https://user-images.githubusercontent.com/2631789/55271726-03756080-52f5-11e9-86f8-8de795575432.png)

**Comment by Tatamo** [comment]
当該コミットで誤ってブロックスコープ内に `let` で別の変数を作ってしまっているのが原因のようです。申し訳ありません。
修正を行いたいと思います。
