### ISSUE TITLE
シューティング正男で子機アイテムを取った時にファイアボール、しっぽで倒すタイプのボスが現れると、ボスのHPが最大値より大きくなる

### ISSUE THREAD

**Issue by urotaichi** [Ryo-9399/mc_canvas#85]
条件
j_tokugi　14（シューティングモード）
boss_destroy_type　2(ボスの倒し方はファイヤーボール，しっぽ)
この状態で文字「l」で出てくるアイテムを取ってボス戦を始めるとボスのHPが最大値より20大きくなります。
![image](https://user-images.githubusercontent.com/2631789/55271809-63b8d200-52f6-11e9-9e22-65073cfeb8cb.png)
Java版から存在するバグだそうです。

**Comment by bikkuri7** [comment]
補足すると，
文字「l」のアイテムを1つ取った状態でボス戦開始→ボスのHPが+10
文字「l」のアイテムを2つ以上取った状態でボス戦開始→ボスのHPが+20
となります。

**Comment by Tatamo** [comment]
ボスのHPの最大値が増えるのが仕様で、HP最大値の表示が更新されていないのがバグではないでしょうか？

**Comment by urotaichi** [comment]
強化アイテムを取るとボスのHPの最大値が増えるのはどこにも明記されていないですがおそらく仕様だと思います。（難易度調整のため？）
現在の仕様のままだとボスのHPが最大値を上回ってしまうという不自然な格好のため、HP最大値の表示が更新されていないのがバグという認識でよろしいと思います。
表示を少し変えるだけならゲーム性に特に影響をもたらさないと思うので、Java版から存在するバグではありますが、互換性を考慮せず修正してしまったほうが良いのではと思います。

**Comment by Tatamo** [comment]
個人的には、このバグの修正には反対です。

ボスのHPが最大値よりも増加した場合、当然タイトルに戻るとボスの最大HPは元に戻ります。
そのため、ボスのHPは、「HPの最大値」と「現在のHP」という二つの変数によって管理されています。

このバグを修正する方法は2通り考えられます。
まず、「暫定的なHPの最大値」を表す変数を追加することです。
タイトルに戻った際にもともとのHP最大値に戻すためには、このように変数を1つ追加する必要があると思います。
とはいえ、現状の`MainProgram`を見るに、これ以上変数を増やしたくないという気持ちがあります。
この表示バグのためだけに変数を増やして状態管理のコストを増やすよりは、この挙動を残しておくほうが比較的良いのではないかと思います。

もう一つの方法としては、「現在のボスのHPがHP最大値を超えていた場合、そちらを最大値として表示する」という手段が考えられます。
こちらは変数を追加しなくてよいという利点がありますが、JSSの`setBossHP`の挙動にも影響するので、単なるバグ修正以上に互換性に影響を与えることが予想されます。
