### ISSUE TITLE
円に亀が乗るとフリーズする

### ISSUE THREAD

**Issue by uhyo** [Ryo-9399/mc_canvas#86]
ぼうしさんによる報告

> masaospaceのエディターでやってみたところ
第3版マップデータの番号でいうと
1123 1124 1138 1139 1140 1141 の円に66の亀が乗るとフリーズします。

> けーてん.さんから聞いたのですが、円に亀が乗るとフリーズは
以前のバージョンのrounddown関数の置き換え忘れが原因みたいです。
多分今のバージョンではObject(r.f)がそれだと思います。

**Comment by shpqg** [comment]
EnemyControllerでrounddownをimportしていないことが原因に見えるためPRを投げようと思ったのですが，何らかの置き換えをしている最中なのでしょうか？

**Comment by Tatamo** [comment]
> 何らかの置き換えをしている最中なのでしょうか？

@Ryo-9399

**Comment by Ryo-9399** [comment]
いいえ、置き換えはしていません。PRを投げてもらっても大丈夫です。
