### ISSUE TITLE
ブックマークレット機能の提案

### ISSUE THREAD

**Issue by na2hiro** [Ryo-9399/mc_canvas#9]
まだまだCanvas正男が正男サイト運営者に知られていないため，プレイヤーが自らアプレットを置換したいケースが発生すると思われます．
そこで，ブックマークを開くとページ内の正男が全てCanvasに置換されるブックマークレットを提案します．

実装の方は単純で，次のようにCanvasMasao.jsを読み込んでreplaceAllを呼び出せばいいのですが，

```
javascript:var s=document.createElement("script");s.src="http://na2hiro.github.io/mc_canvas/CanvasMasao.js";s.onload=function(){CanvasMasao.Game.replaceAll()};document.body.appendChild(s);void 0;
```

相談したいのはCanvasMasao.jsの置き場です．
流石にブックマークレットのURL中にCanvasMasao.jsソース800KBを埋め込むのは非現実的なので，どこかのWeb上に置くことになります．

現在，na2hiro/mc_canvasリポジトリ上でGithub Pages機能を用いて提供しています． http://na2hiro.github.io/mc_canvas/CanvasMasao.js
これは，リポジトリにgh-pagesという名前のブランチがある場合，"http://アカウント名.github.io/リポジトリ名/"以下に公開されるという機能です．
もし公式リポジトリ上で提供できるのでしたらしていただきたいです．
その後上のブックマークレットのURLを変更した上で公式機能としてREADME等に記載しようと思います．
na2hiroが生きていてgh-pagesの反映を怠らない限りは，現状通りna2hiro/mc_canvasでCanvasMasao.jsの提供をしても問題はないと思いますが．

gh-pagesによる提供の方法
- (最初)masterからgh-pagesブランチを作成
- (master更新後などブックマークレット反映時)gh-pagesでmasterをマージし，gh-pagesの内容を最新にする

若干手間ですし，反映を忘れても旧バージョンのままになるだけなので，大きなアップデートの後など気が向いた時に反映する程度で問題ないかとは思います．

RYOさんのgh-pagesを使うか，na2hiroのほうを使うか，また別の方法がいいか，お伺いしたいです．

**Comment by urotaichi** [comment]
JS版まさお変換ブックマークレット FXで変換対象となる正男に
1.object要素を使用した正男
2.MasaoKani2.classを使用した正男
を追加してほしいです。よろしくお願いします。

**Comment by Ryo-9399** [comment]
(CanvasMasao.)Game.replaceAllメソッドの置換対象に、Object要素を使用したまさお、MasaoKani(2).classを使用したまさおを追加しました。ブックマークレットについてですが、MasaoKani(2).classの追加により、JSファイルを読み込みする数が２つになるので、ブックマークレットそのものの変更が必要になります。変更したブックマークレットについては、後日README等にまとめようと思います。
