### ISSUE TITLE
コイン全取得時降りられる坂が一瞬だけ鉄の坂になる

### ISSUE THREAD

**Issue by boshi-s-lab** [Ryo-9399/mc_canvas#93]
クリア条件をコイン全て取ったら脱出ハシゴにして、コインを全てとった時
下キーで降りられる坂が一瞬鉄の坂になります。
明らかに不自然な挙動なのでコイン全取得時も見た目が変わらないようにするべきです。

見た目が変わっているだけなのか、オブジェクトごと変わっているのかは検証方法が思いつかず未検証です。

参考例：https://masao.space/play/1652

**Comment by bikkuri7** [comment]
Java版でも同様の現象が発生することを確認しました。

下のステージ（ひたすら右に歩く設定で↓キーを押し続ける）を用いてゲームスピードを遅くして1フレームごとに確認してみたところ，2つとも正男が全く同じところを通っているので，坂道の見た目だけが変わっていると思われます。
なお，この画像の通り，クリア条件を「コインを全部取ると脱出ハシゴ出現」にしてコインを置かなかった場合，ステージ開始直後の1フレームにおいても鉄の坂の表示になることが新たに分かりました。
![a](https://user-images.githubusercontent.com/3896058/57315283-38fc3d80-712e-11e9-96d7-aecc06bb5b47.gif)

**Comment by urotaichi** [comment]
https://github.com/Ryo-9399/mc_canvas/pull/120 でついでに修正しておきました。
