### ISSUE TITLE
グラーダの攻撃方法を変更するとフリーズするバグ

### ISSUE THREAD

**Issue by urotaichi** [Ryo-9399/mc_canvas#94]
2573d9f から発生しているようです。
Internet Explorerでのみ、`boss_type`が2～5の時にフリーズします。

**Comment by Tatamo** [comment]
Babelの最新バージョンを使えばレガシーブラウザで動作しないコードに対して必要に応じてpolyfillを適用できる https://babeljs.io/blog/2019/03/19/7.4.0 ため、Babelの更新に合わせて対応を行いました。
